### ISSUE TITLE
USER STORY: Account Registration

### ISSUE THREAD

**Issue by Evan2022** [Evan2022/Trading-Journal#1]
As a **User** I can **Register for an account** so that **I can record my own trading data**.

**ACCEPTANCE CRITERIA:**

1. Registration form must include email, password, password match and username. 
2. User must receive confirmation their account has been created. 
3. After registering for a account they must show as logged in while on the site. 

**TASKS:**

- [x] 1. Add sign up/register button. 
- [x] 2. Create form fields, email, password, username. 
- [x] 3. Create confirmation message to user once account created. 
- [x] 4. Style the form.

**Comment by Evan2022** [comment]
Confirmation message working, all steps complete.
