### ISSUE TITLE
USER STORY: Login 

### ISSUE THREAD

**Issue by Evan2022** [Evan2022/Trading-Journal#2]
As a **User** I can **Login to my existing account** so that **I can access my saved trading data, update, delete and record more data if I want to**. 

**ACCEPTANCE CRITERIA:**

1. Login form must include username/email and password.
2. User should have the option for forget password and the option for remember me. 
3. Once the user is logged in their login status should show. 

**TASKS:**

- [x] 1. Add Login button. 
- [x] 2. Create form fields, email/username and password, . 
- [x] 3. Add forgot password option for the user.  
- [x] 4. Change login status once logged in. 
- [x] 5. Style the form.

**Comment by Evan2022** [comment]
Django Allauth package used, comes with 1-4 tasks included

**Comment by Evan2022** [comment]
Remove remember login details option. Complete Login.
