### ISSUE TITLE
USER STORY: CRUD Trades

### ISSUE THREAD

**Issue by Evan2022** [Evan2022/Trading-Journal#5]
As a User I can Create, Read, Update and Delete Trades so that record new trading data, edit existing data and delete any data which is no longer needed

**ACCEPTANCE CRITERIA:**

1. Existing Trades need to be displayed to the User. 
2. User must have the option to add a new Trade. 
3. User must have the option to view recorded Trades. 
4. User must have the option to edit existing Trades. 
5. User must have the option to delete existing Trades. 
6. Trade model needs to be updated.

**TASKS:**

- [x] 1. Update Trade Model with correct fields.
- [x] 2. Create Trades html page. 
- [x] 3. Display existing Trades to the User. 
- [x] 4. Add option for user to add a new Trade.
- [x] 5. Add option for user to View existing Trade Data
- [x] 6. Add option for user to edit Trade fields.
- [x] 7. Add option for user to delete existing Trades.

**Comment by Evan2022** [comment]
Trade model working correctly, may add additional fields in the future, trades page set up and trades displayed to the user, Add trade option created and working.

**Comment by Evan2022** [comment]
CRUD completed, read, update and delete all working.
