### ISSUE TITLE
USER STORY: Website Footer

### ISSUE THREAD

**Issue by Evan2022** [Evan2022/Trading-Journal#7]
As a **User** I can **see the company's contact details** so that **I can easily get in touch with the company and know more about it.**

**ACCEPTANCE CRITERIA:**

1. The footer should contain the company's logo and © mark, along with the year established. 
2. The footer should be visible on all pages of the website.
3. The footer should contain the company's phone number, email, and physical address.

**TASKS:**

- [x] 1. Design a responsive footer adjustable for all screen sizes.
- [x] 2. Include the company name, © mark and date established at the top of the footer. 
- [x] 3. Note the company contact details on the footer. 
- [x] 4. Test the footer's responsiveness.
